target = "https://www.rfc-editor.org/rfc/rfc8259#section-6"

# Section 6 of the RFC is about number format:
# 6.  Numbers
#
#    The representation of numbers is similar to that used in most
#    programming languages.  A number is represented in base 10 using
#    decimal digits.  It contains an integer component that may be
#    prefixed with an optional minus sign, which may be followed by a
#    fraction part and/or an exponent part.  Leading zeros are not
#    allowed.
#
#    A fraction part is a decimal point followed by one or more digits.
#
#    An exponent part begins with the letter E in uppercase or lowercase,
#    which may be followed by a plus or minus sign.  The E and optional
#    sign are followed by one or more digits.
#
#    Numeric values that cannot be represented in the grammar below (such
#    as Infinity and NaN) are not permitted.
#
#       number = [ minus ] int [ frac ] [ exp ]
#       decimal-point = %x2E       ; .
#       digit1-9 = %x31-39         ; 1-9
#       e = %x65 / %x45            ; e E
#
#       exp = e [ minus / plus ] 1*DIGIT
#       frac = decimal-point 1*DIGIT
#       int = zero / ( digit1-9 *DIGIT )
#       minus = %x2D               ; -
#       plus = %x2B                ; +
#       zero = %x30                ; 0
#
#    This specification allows implementations to set limits on the range
#    and precision of numbers accepted.  Since software that implements
#    IEEE 754 binary64 (double precision) numbers [IEEE754] is generally
#    available and widely used, good interoperability can be achieved by
#    implementations that expect no more precision or range than these
#    provide, in the sense that implementations will approximate JSON
#    numbers within the expected precision.  A JSON number such as 1E400
#    or 3.141592653589793238462643383279 may indicate potential
#    interoperability problems, since it suggests that the software that
#    created it expects receiving software to have greater capabilities
#    for numeric magnitude and precision than is widely available.
#
#    Note that when such software is used, numbers that are integers and
#    are in the range [-(2**53)+1, (2**53)-1] are interoperable in the
#    sense that implementations will agree exactly on their numeric
#    values.

# High level number grammar
[[spec]]
level = "MUST"
quote = '''
number = [ minus ] int [ frac ] [ exp ]
'''

# Track the grammar for an int
[[spec]]
level = "MUST"
quote = '''
int = zero / ( digit1-9 *DIGIT )
'''

# Track the grammar for a frac
[[spec]]
level = "MUST"
quote = '''
frac = decimal-point 1*DIGIT
'''

# Track the exponent format
[[spec]]
level = "MUST"
quote = '''
exp = e [ minus / plus ] 1*DIGIT
'''
